### ISSUE TITLE
Import BMI wording 

### ISSUE THREAD

**Issue by alisonw4w4** [SIGDAO/bettermi#18]
<img width="520" alt="Screenshot 2024-03-21 at 2 06 44 PM" src="https://github.com/SIGDAO/Bettermi/assets/156061166/739fbcac-1890-470d-b5af-b7e8e6dfc9a9">
The screen when user upload BMI after sign-up, wording should change from "minting" to "importing"

**Comment by cychiuak** [comment]
Fixed
